### ISSUE TITLE
case "TestMonitoringStackController/Verify_multi-namespace_support" failed on OCP 4.14

### ISSUE THREAD

**Issue by lihongyan1** [rhobs/observability-operator#311]
```
./test/run-e2e-ocp.sh
......
=== RUN   TestMonitoringStackController/Verify_multi-namespace_support
    monitoring_stack_controller_test.go:850: assertion failed: error is not nil: failed to create demo app test-ns-1/prometheus: pods "prometheus" is forbidden: violates PodSecurity "restricted:v1.24": allowPrivilegeEscalation != false (container "prometheus" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "prometheus" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "prometheus" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "prometheus" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost"): test-ns-1: deploying demo app failed
--- FAIL: TestMonitoringStackController (382.73s)
```
% oc version
Client Version: 4.13.1
Kustomize Version: v4.5.7
Server Version: 4.14.0-0.nightly-2023-07-11-092038
Kubernetes Version: v1.27.3+af29f64

It's a automation code issue, will fix it following solution
https://access.redhat.com/solutions/7002730

**Comment by lihongyan1** [comment]
After applying fix in solution https://access.redhat.com/solutions/7002730
Get the following error
```
% oc logs prometheus
......
ts=2023-07-14T02:48:02.307Z caller=query_logger.go:91 level=error component=activeQueryTracker msg="Error opening query log file" file=/prometheus/queries.active err="open /prometheus/queries.active: permission denied"
panic: Unable to create mmap-ed active query log

goroutine 1 [running]:
github.com/prometheus/prometheus/promql.NewActiveQueryTracker({0x7ffe3121adca, 0xb}, 0x14, {0x3aba480, 0xc000859540})
	/app/promql/query_logger.go:121 +0x3cd
main.main()
	/app/cmd/prometheus/main.go:605 +0x6773
```
